kind: pipeline
type: docker
name: default

volumes:
- name: data
  temp: {}
- name: tmp
  temp: {}

steps:
- name: download_xapk
  image: plugins/download
  volumes:
  - name: tmp
    path: /tmp
  settings:
    source: 
      from_secret: eve_xapk_url
    destination: /tmp/eve.xapk

- name: dump_static
  image: cookiemagic/evee-tools
  volumes:
  - name: data
    path: /data
  - name: tmp
    path: /tmp
  commands:
  - mkdir -p /data/staticdata
  - export PATH=$PATH:/opt/eve-echoes-tools/scripts
  - export PATH="$HOME/.cargo/bin:$PATH"
  - python3 /opt/eve-echoes-tools/scripts/dump_static_data.py /tmp/eve.xapk /data/staticdata

- name: extract_npk
  image: busybox
  volumes:
  - name: data
    path: /data
  - name: tmp
    path: /tmp
  commands:
  - mkdir -p /tmp/npk
  - mkdir -p /tmp/eve
  - unzip /tmp/eve.xapk -d /tmp/eve
  - unzip /tmp/eve/Android/obb/com.netease.eve.en/main.57.com.netease.eve.en.obb
  - cd /tmp/eve/Android/obb/com.netease.eve.en/main.57.com.netease.eve.en
  - find . -type f -name '*.npk' | mv {} /data/npk

- name: clone_npk_tool
  image: alpine/git
  volumes:  
  - name: tmp
    path: /tmp
  commands:
  - git clone https://github.com/xforce/neox-tools.git /tmp/neox-tools

- name: extract_ktx
  image: rust
  volumes:
  - name: data
    path: /data
  - name: tmp
    path: /tmp
  commands:
  - mkdir -p /data/ktx
  - cd /tmp/neox-tools
  - cargo install --path .  
  - find /data/npk -type f -name "*.npk" -exec npktool x {} \;
  - mv out /data/ktx

- name: convert_ktx_to_png
  image: madhead/imagemagick
  volumes:
  - name: data
    path: /data
  commands:
  - mkdir -p /data/png
  - convert /data/ktx/*.ktx /data/png/*.png
