kind: pipeline
type: docker
name: default


volumes:
- name: data
  temp: {}
- name: tmp
  temp: {}


steps:
- name: download_xapk
  image: plugins/download
  volume:
  - name: tmp
    path: /tmp
  environment:
  settings:
    source: 
      from_secret: eve_xapk_url
    destination: /tmp/eve.xapk

- name: dump_static
  image: cookiemagic/evee-tools
  volume:
  - name: data
    path: /data
  - name: tmp
    path: /tmp
  commands:
  - mkdir -p /data/staticdata
  - python3 /opt/eve-echoes-tools/scripts/dump_static_data.py /tmp/eve.xapk /data/staticdata

- name: extract_npk
  image: busybox
  volume:
  - name: data
    path: /data
  - name: tmp
    path: /tmp
  commands:
  - mkdir -p /tmp/npk
  - unzip /tmp/eve.xapk -d /tmp/eve.xapk
  - unzip /tmp/eve.xapk/Android/obb/com.netease.eve.en/com.netease.eve.en.obb /tmp/npk
  - mv /tmp/npk/*.npk /data/npk

- name: clone_npk_tool
  image: alpine/git
  commands:
  - git clone https://github.com/xforce/neox-tools.git .

- name: extract_ktx
  image: rust
  volume:
  - name: data
    path: /data
  commands:
  - mkdir -p /data/ktx
  - cargo install --path .
  - npktool x /data/npk/*.npk
  - mv out /data/ktx

- name: convert_ktx_to_png
  image: madhead/imagemagick
  volume:
  - name: data
    path: /data
  commands:
  - mkdir -p /data/png
  - convert /data/ktx/* /data/png/*.png