kind: pipeline
type: docker
name: default


volumes:
- name: data
  temp: {}
- name: tmp
  temp: {}


steps:
- name: download_xapk
  image: plugins/download
  volumes:
  - name: tmp
    path: /tmp
  settings:
    source: 
      from_secret: eve_xapk_url
    destination: /tmp/eve.xapk

- name: dump_static
  image: cookiemagic/evee-tools
  volumes:
  - name: data
    path: /data
  - name: tmp
    path: /tmp
  commands:
  - mkdir -p /data/staticdata
  - python3 /opt/eve-echoes-tools/scripts/dump_static_data.py /tmp/eve.xapk /data/staticdata

- name: extract_npk
  image: busybox
  volumes:
  - name: data
    path: /data
  - name: tmp
    path: /tmp
  commands:
  - mkdir -p /tmp/npk
  - mkdir -p /tmp/eve
  - unzip /tmp/eve.xapk -d /tmp/eve
  - unzip /tmp/eve/Android/obb/com.netease.eve.en/main.57.com.netease.eve.en.obb /tmp/npk
  - mv /tmp/npk/main.57.com.netease.eve.en/*.npk /data/npk

- name: clone_npk_tool
  image: alpine/git
  commands:
  - git clone https://github.com/xforce/neox-tools.git .

- name: extract_ktx
  image: rust
  volumes:
  - name: data
    path: /data
  commands:
  - mkdir -p /data/ktx
  - cargo install --path .
  - npktool x /data/npk/*.npk
  - mv out /data/ktx

- name: convert_ktx_to_png
  image: madhead/imagemagick
  volumes:
  - name: data
    path: /data
  commands:
  - mkdir -p /data/png
  - convert /data/ktx/* /data/png/*.png
