kind: pipeline
type: docker
name: default


volumes:
- name: data
  host:
    path: $(pwd)/data
- name: tmp
  temp: {}


steps:
- name: download_xapk
  image: busybox
  volume:
  - name: data
    path: /data
  - name: tmp
    path: /tmp
  environment:
    EVE_XAPK_URL:
      from_secret: eve_xapk_url
  commands:
  - wget "$${EVE_APK_URL}" -O /tmp/eve.xapk

- name: dump_static
  image: cookiemagic/evee-tools
  volume:
  - name: data
    path: /data
  - name: tmp
    path: /tmp
  commands:
  - python3 /opt/eve-echoes-tools/scripts/dump_static_data.py /tmp/eve.xapk /data/staticdata

- name: extract_npk
  image: busybox
  volume:
  - name: data
    path: /data
  - name: tmp
    path: /tmp
  commands:
  - unzip /tmp/eve.xapk -d /tmp/eve.xapk
  - unzip /tmp/eve.xapk/Android/obb/com.netease.eve.en/com.netease.eve.en.obb /tmp/obb
  - mv /tmp/obb/*.npk /data/npk

- name: clone_npk_tool
  image: alpine/git
  commands:
  - git clone https://github.com/xforce/neox-tools.git .

- name: extract_ktx
  image: rust
  volume:
  - name: data
    path: /data
  commands:
  - cargo install --path .
  - npktool x /data/npk/*.npk
  - mv out /data/ktx